sudo: required
language: ruby
env:
  global:
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
addons:
  apt:
    packages:
      - docker-ce
  ssh_known_hosts: ec2-35-158-221-148.eu-central-1.compute.amazonaws.com
services:
  - docker

script:
  - docker-compose -f scripts/app.yml build