version: '3'

services:
  dotnet-agent-portal-gateway:
    build: 
      context: ../
      dockerfile: AgentPortalApiGateway/Dockerfile
    image: dotnet-agent-portal-gateway
    container_name: dotnet-agent-portal-gateway
    ports:
    - 8099:8099

  dotnet-auth-service:
    build: 
      context: ../
      dockerfile: AuthService/Dockerfile
    image: dotnet-auth-service
    container_name: dotnet-auth-service
    ports:
    - 6060:6060
  
  dotnet-chat-service:
    build: 
      context: ../
      dockerfile: ChatService/Dockerfile
    image: dotnet-chat-service
    container_name: dotnet-chat-service
    ports:
    - 4099:4099

  dotnet-payment-service:
    build: 
      context: ../
      dockerfile: PaymentService/Dockerfile
    image: dotnet-payment-service
    container_name: dotnet-payment-service
    ports:
    - 5070:5070

  dotnet-policy-search-service:
    build: 
      context: ../
      dockerfile: PolicySearchService/Dockerfile
    image: dotnet-policy-search-service
    container_name: dotnet-policy-search-service
    ports:
    - 5065:5065

  dotnet-policy-service:
    build: 
      context: ../
      dockerfile: PolicyService/Dockerfile
    image: dotnet-policy-service
    container_name: dotnet-policy-service
    ports:
    - 5050:5050

  dotnet-pricing-service:
    build: 
      context: ../
      dockerfile: PricingService/Dockerfile
    image: dotnet-pricing-service
    container_name: dotnet-pricing-service
    ports:
    - 5040:5040

  dotnet-product-service:
    build: 
      context: ../
      dockerfile: ProductService/Dockerfile
    image: dotnet-product-service
    container_name: dotnet-product-service
    ports:
    - 5030:5030

  dotnet-dashboard-service:
    build: 
      context: ../
      dockerfile: DashboardService/Dockerfile
    image: dotnet-dashboard-service
    container_name: dotnet-dashboard-service
    ports:
    - 5035:5035

  dotnet-web-vue:
    build: ../Web
    image: dotnet-web-vue
    container_name: dotnet-web-vue
    ports:
    - 8080:80
